- name: 5.1 Ensure AppArmor Profile is Enabled (Scored)
  debug: msg="Start Docker with --security-opt apparmor=docker-default"
  tags:
   - scored
   - section5.1

- name: 5.2 Ensure SELinux security options are set, if applicable (Scored)
  jsonpatch: 
    file: "{{ config_file }}"
    key: selinux-enabled
    value: true
  notify: Reload docker
  tags:
   - scored
   - section5.2

#- name: 5.3 Ensure Linux Kernel Capabilities are restricted within containers (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.3
#
#- name: 5.4 Ensure privileged containers are not used (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.4
#
#- name: 5.5 Ensure sensitive host system directories are not mounted on containers (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.5
#
#- name: 5.6 Ensure ssh is not run within containers (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.6
#
#- name: 5.7 Ensure privileged ports are not mapped within containers (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.7

- name: 5.8 Ensure only needed ports are open on the container (Scored)
  debug: msg="Use the -p (lowercase) or --publish flag to explicitly define the ports that you need for a particular container instance."
  shell: docker ps --quiet | xargs docker inspect --format '{{ .Id }}: Ports={{ .NetworkSettings.Ports }}'
  tags:
   - scored
   - section5.8

#- name: 5.9 Ensure the host's network namespace is not shared (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.9

- name: 5.10 Ensure memory usage for container is limited (Scored)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - scored
   - section5.10

- name: 5.11 Ensure CPU priority is set appropriately on the container (Scored)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - scored
   - section5.11

- name: 5.12 Ensure the container's root filesystem is mounted as read only (Scored)
  debug: msg="Start Docker with --read-only option"
  shell: docker ps --quiet --all | xargs docker inspect --format '{{ .Name }}: ReadonlyRootfs={{ .HostConfig.ReadonlyRootfs }}' | awk -F\/ '{print $2}' | awk -F\: '{print $1}'
  register: docker_names 
  docker_container:
    name: "{{ item }}"
    with_items: "{{ docker_names }}"
    read_only: yes
  tags:
   - scored
   - section5.12

- name: 5.13 Ensure incoming container traffic is binded to a specific host interface (Scored)
  debug: msg="Need to replace wildcard IP address 0.0.0.0 with specific host interface."
  shell: docker ps --quiet | xargs docker inspect --format '{{ .Id }}: Ports={{ .NetworkSettings.Ports }}'
  tags:
   - scored
   - section5.13

- name: 5.14 Ensure 'on-failure' container restart policy is set to '5' (Scored)
  debug: msg="Values should be RestartPolicyName=no and just RestartPolicyName= or RestartPolicyName=on-failure and MaximumRetryCount=<5"
  shell: docker ps --quiet --all | xargs docker inspect --format '{{ .Id }}: RestartPolicyName={{ .HostConfig.RestartPolicy.Name }} MaximumRetryCount={{ .HostConfig.RestartPolicy.MaximumRetryCount }}'
  tags:
   - scored
   - section5.14

#- name: 5.15 Ensure the host's process namespace is not shared (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.15
#
#- name: 5.16 Ensure the host's IPC namespace is not shared (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.16
#
#- name: 5.17 Ensure host devices are not directly exposed to containers (Not Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - not_scored
#   - section5.17

- name: 5.18 Ensure the default ulimit is overwritten at runtime, only if needed (Not Scored)
  debug: msg="Should return Ulimits=<no value> for each container instance. Only override the default ulimit settings if needed."
  shell: docker ps --quiet --all | xargs docker inspect --format '{{ .Id }}: Ulimits={{ .HostConfig.Ulimits }}'
  tags:
   - not_scored
   - section5.18

#- name: 5.19 Ensure mount propagation mode is not set to shared (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.19
#
#- name: 5.20 Ensure the host's UTS namespace is not shared (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.20
#
#- name: 5.21 Ensure the default seccomp profile is not Disabled (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.21

- name: 5.22 Ensure docker exec commands are not used with privileged option (Scored)
  debug: msg="Do not use --privileged option in docker exec command."
  shell: ausearch -k docker | grep exec | grep privileged
  tags:
   - scored
   - section5.22

- name: 5.23 Ensure docker exec commands are not used with user option (Scored)
  debug: msg="Do not use --user option in docker exec command."
  shell: ausearch -k docker | grep exec | grep user
  tags:
   - scored
   - section5.23

#- name: 5.24 Ensure cgroup usage is confirmed (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.24
   
- name: 5.25 Ensure the container is restricted from acquiring additional privileges (Scored)
  debug: msg="Security options currently configured for the containers should include no-new-privileges. See Control 2.18"
  shell: docker ps --quiet --all | xargs docker inspect --format '{{ .Id }}: SecurityOpt={{ .HostConfig.SecurityOpt }}'
  tags:
   - scored
   - section5.25

- name: 5.26 Ensure container health is checked at runtime (Scored)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - scored
   - section5.26

- name: 5.27 Ensure docker commands always get the latest version of the image (Not Scored)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - not_scored
   - section5.27

- name: 5.28 Ensure PIDs cgroup limit is used (Scored)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - scored
   - section5.28

#- name: 5.29 Ensure Docker's default bridge docker0 is not used (Not Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.29
#
#
#- name: 5.30 Ensure the host's user namespaces is not shared (Scored)
#  debug: msg="This is configuration is set when containers are run"
#  tags:
#   - scored
#   - section5.30

- name: 5.31 Ensure the Docker socket is not mounted inside any containers (Scored)
  debug: msg="This is configuration is set when containers are run"
  tags:
   - scored
   - section5.31
